# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: authentication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'authentication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x05steam\"\xdc\x01\n\x1d\x43\x41uthentication_DeviceDetails\x12\x1c\n\x14\x64\x65vice_friendly_name\x18\x01 \x01(\t\x12\x34\n\rplatform_type\x18\x02 \x01(\x0e\x32\x1d.steam.EAuthTokenPlatformType\x12\x0f\n\x07os_type\x18\x03 \x01(\x05\x12\x1a\n\x12gaming_device_type\x18\x04 \x01(\r\x12\x14\n\x0c\x63lient_count\x18\x05 \x01(\r\x12\x12\n\nmachine_id\x18\x06 \x01(\x0c\x12\x10\n\x08\x61pp_type\x18\x07 \x01(\x05\"\xd5\x01\n-CAuthentication_BeginAuthSessionViaQR_Request\x12\x1c\n\x14\x64\x65vice_friendly_name\x18\x01 \x01(\t\x12\x34\n\rplatform_type\x18\x02 \x01(\x0e\x32\x1d.steam.EAuthTokenPlatformType\x12<\n\x0e\x64\x65vice_details\x18\x03 \x01(\x0b\x32$.steam.CAuthentication_DeviceDetails\x12\x12\n\nwebsite_id\x18\x04 \x01(\t\"~\n.CAuthentication_BeginAuthSessionViaQR_Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x0c\x12\x12\n\nrequest_id\x18\x03 \x01(\x0c\x12\x15\n\rchallenge_url\x18\x04 \x01(\t\"\xcb\x01\n?CAuthentication_UpdateAuthSessionWithMobileConfirmation_Request\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x04\x12\x0f\n\x07steamid\x18\x03 \x01(\x06\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x0f\n\x07\x63onfirm\x18\x05 \x01(\x08\x12/\n\x0bpersistence\x18\x06 \x01(\x0e\x32\x1a.steam.ESessionPersistence\"R\n@CAuthentication_UpdateAuthSessionWithMobileConfirmation_Response\x12\x0e\n\x06result\x18\x01 \x01(\x05*\xb9\x01\n\x16\x45\x41uthTokenPlatformType\x12$\n k_EAuthTokenPlatformType_Unknown\x10\x00\x12(\n$k_EAuthTokenPlatformType_SteamClient\x10\x01\x12\'\n#k_EAuthTokenPlatformType_WebBrowser\x10\x02\x12&\n\"k_EAuthTokenPlatformType_MobileApp\x10\x03*`\n\x13\x45SessionPersistence\x12$\n k_ESessionPersistence_Persistent\x10\x00\x12#\n\x1fk_ESessionPersistence_Temporary\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EAUTHTOKENPLATFORMTYPE']._serialized_start=889
  _globals['_EAUTHTOKENPLATFORMTYPE']._serialized_end=1074
  _globals['_ESESSIONPERSISTENCE']._serialized_start=1076
  _globals['_ESESSIONPERSISTENCE']._serialized_end=1172
  _globals['_CAUTHENTICATION_DEVICEDETAILS']._serialized_start=32
  _globals['_CAUTHENTICATION_DEVICEDETAILS']._serialized_end=252
  _globals['_CAUTHENTICATION_BEGINAUTHSESSIONVIAQR_REQUEST']._serialized_start=255
  _globals['_CAUTHENTICATION_BEGINAUTHSESSIONVIAQR_REQUEST']._serialized_end=468
  _globals['_CAUTHENTICATION_BEGINAUTHSESSIONVIAQR_RESPONSE']._serialized_start=470
  _globals['_CAUTHENTICATION_BEGINAUTHSESSIONVIAQR_RESPONSE']._serialized_end=596
  _globals['_CAUTHENTICATION_UPDATEAUTHSESSIONWITHMOBILECONFIRMATION_REQUEST']._serialized_start=599
  _globals['_CAUTHENTICATION_UPDATEAUTHSESSIONWITHMOBILECONFIRMATION_REQUEST']._serialized_end=802
  _globals['_CAUTHENTICATION_UPDATEAUTHSESSIONWITHMOBILECONFIRMATION_RESPONSE']._serialized_start=804
  _globals['_CAUTHENTICATION_UPDATEAUTHSESSIONWITHMOBILECONFIRMATION_RESPONSE']._serialized_end=886
# @@protoc_insertion_point(module_scope)
